"""empty message

Revision ID: 3ff71b2cbf19
Revises: 
Create Date: 2023-10-19 09:10:38.049059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff71b2cbf19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_permissao_descricao', table_name='permissao')
    op.drop_index('ix_permissao_id_permissao', table_name='permissao')
    op.drop_table('permissao')
    op.drop_index('ix_produto_descricao', table_name='produto')
    op.drop_index('ix_produto_id_produto', table_name='produto')
    op.drop_index('ix_produto_materia_prima', table_name='produto')
    op.drop_index('ix_produto_publico', table_name='produto')
    op.drop_index('ix_produto_quantidade', table_name='produto')
    op.drop_table('produto')
    op.drop_index('ix_usuario_id_usuario', table_name='usuario')
    op.drop_index('ix_usuario_senha', table_name='usuario')
    op.drop_index('ix_usuario_username', table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('senha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id_permissao', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_permissao'], ['permissao.id_permissao'], name='usuario_id_permissao_fkey'),
    sa.PrimaryKeyConstraint('id_usuario', name='usuario_pkey')
    )
    op.create_index('ix_usuario_username', 'usuario', ['username'], unique=False)
    op.create_index('ix_usuario_senha', 'usuario', ['senha'], unique=False)
    op.create_index('ix_usuario_id_usuario', 'usuario', ['id_usuario'], unique=False)
    op.create_table('produto',
    sa.Column('id_produto', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publico', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('materia_prima', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_produto', name='produto_pkey')
    )
    op.create_index('ix_produto_quantidade', 'produto', ['quantidade'], unique=False)
    op.create_index('ix_produto_publico', 'produto', ['publico'], unique=False)
    op.create_index('ix_produto_materia_prima', 'produto', ['materia_prima'], unique=False)
    op.create_index('ix_produto_id_produto', 'produto', ['id_produto'], unique=False)
    op.create_index('ix_produto_descricao', 'produto', ['descricao'], unique=False)
    op.create_table('permissao',
    sa.Column('id_permissao', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_permissao', name='permissao_pkey')
    )
    op.create_index('ix_permissao_id_permissao', 'permissao', ['id_permissao'], unique=False)
    op.create_index('ix_permissao_descricao', 'permissao', ['descricao'], unique=False)
    # ### end Alembic commands ###
